name: test-boot
description: 'Process test bootstrap build by OW (for test compatibility)'
inputs:
  hostos:
    description: 'host os'
    required: false
    default: ''
    type: string
  gitpath:
    description: 'git subdirectory'
    required: false
    default: ''
    type: string
  owdebug:
    description: 'verbosed/debug output for GH Actions scripts development'
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - name: Open Watcom setup
    uses: open-watcom/setup-watcom@v0
    with:
      version: 1.9
  - if: inputs.hostos == 'lnx'
    name: Test Bootstrap OW
    run: ci/buildx.sh
    env:
      OWBUILD_STAGE: 'boot'
      OWTOOLS:       'WATCOM'
      OWROOT:        ${{ github.workspace }}
      OWDEBUG:       ${{ inputs.owdebug }}
      OWVERBOSE:     1
    shell: bash
  - if: inputs.hostos == 'nt'
    name: Test Bootstrap OW
    run: ci/buildx.cmd
    env:
      OWBUILD_STAGE: 'boot'
      OWTOOLS:       'WATCOM'
      OWROOT:        ${{ github.workspace }}
      OWDEBUG:       ${{ inputs.owdebug }}
      OWVERBOSE:     1
    shell: cmd
